name: Build and Push Docker Image

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: distributed-node
      IMAGE_TAG: latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker image and push to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          ./mvnw clean compile jib:dockerBuild
          docker tag distributed-file-server:0.0.1-SNAPSHOT ghcr.io/scatterrr-cse19/$IMAGE_NAME:$IMAGE_TAG
          docker push ghcr.io/scatterrr-cse19/$IMAGE_NAME:$IMAGE_TAG